### ISSUE TITLE
Arguments checking bug

### ISSUE THREAD

**Issue by 4refr0nt** [arcoirislabs/cordova-plugin-mqtt#21]
If you pass `retain = false` when connect, then `retain` is `true`.
Disabling `retain` flag only if `retain` option is `undefined`

```
                var options = {}
                options.topic = topic;
                options.payload = msg;
                options.qos = 0;
                options.retain = false;
                options.success = function() {};
                options.error = function() {};

                cordova.plugins.CordovaMqTTPlugin.publish(options)
```

**Comment by arcoirislabs** [comment]
We will fix the issue soon

**Comment by snr-lab** [comment]
To fix this bug please update the following line in cordova-plugin-mqtt.js
(args.retain===undefined) ? (args.retain=false) : (args.retain=true);
To
(args.retain===undefined) ? (args.retain=false) : "";

**Comment by arcoirislabs** [comment]
@snr-lab Thank you for the PR. Just wanted to know that have you verified completely ??

**Comment by snr-lab** [comment]
Thank you very much for accepting my PR. 
I am developing an mqtt app and I am verifying the plugin repeatedly. 

I got one bug with my fix when will message is not configured. I have fixed the issue and raised the PR. Please approve it.

**Comment by snr-lab** [comment]
Can we mark this bug as resolved as the issue is fixed?

**Comment by arcoirislabs** [comment]
We need to see for any more errors. Till then let it be open

**Comment by snr-lab** [comment]
I found one more bug. When we set keep alive 0 it automatically get changed to 60000. According to the documentation 0 is also a valid input. It actually disables keep alive feature.

**Comment by spilz87** [comment]
Hello

It seems the issue is still there 
How to merge it in last release ?

**Comment by amaze-escape** [comment]
I can also confirm that the bug is still there...

**Comment by arcoirislabs** [comment]
Can you try this 
https://github.com/ameykshirsagar/cordova-plugin-mqtt
